include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-fleth
PKG_VERSION:=0.2.1
PKG_RELEASE:=1

LUCI_TITLE:=Flet'h configuration helper for QWRT MAP-E
LUCI_DESCRIPTION:=Flet'h-style LuCI helper for QWRT MAP-E auto configuration with Qualcomm PPE acceleration support.
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
