#!/bin/sh

uci -q get fleth.global >/dev/null || uci set fleth.global='fleth'
uci -q get fleth.global.enabled >/dev/null || uci set fleth.global.enabled='1'
uci -q get fleth.global.interface >/dev/null || uci set fleth.global.interface='mape'
uci -q get fleth.global.interface6 >/dev/null || uci set fleth.global.interface6='wan6'
uci -q get fleth.global.interface_zone >/dev/null || uci set fleth.global.interface_zone='wan'
uci -q get fleth.global.mtu >/dev/null || uci set fleth.global.mtu='1460'
uci -q get fleth.global.prefer_slaac >/dev/null || uci set fleth.global.prefer_slaac='1'
uci -q get fleth.global.tunnel_activation >/dev/null || uci set fleth.global.tunnel_activation='1'
uci commit fleth

chmod 755 \
	/usr/sbin/fleth \
	/usr/sbin/fleth-map-e.lua \
	/usr/libexec/fleth-fw4 \
	/lib/netifd/proto/ipip6h.sh \
	/lib/netifd/proto/ipip6hp.sh \
	/usr/share/fleth/firewall.include \
	/usr/share/fleth/ipip6hp-hotplug.sh \
	/usr/share/fleth/map.sh 2>/dev/null

exit 0
